import type { CVSection, EducationEntry } from "./types";
export const education: EducationEntry[] = [
  {
    "institution": "KAIST",
    "degree": "Ph.D. studies",
    "program": "Graduate School of Metaverse",
    "date": "2026.03 – Present",
    "advisorId": "yoon",
    "lab": {
      "name": "HCI Tech Lab",
      "url": "https://hcitech.org/team"
    },
    "organizationId": "kaist"
  },
  {
    "institution": "KAIST",
    "degree": "M.S.",
    "program": "Graduate School of Metaverse",
    "date": "2023.08 – 2026.02",
    "advisorId": "yoon",
    "lab": {
      "name": "HCI Tech Lab",
      "url": "https://hcitech.org/team"
    },
    "organizationId": "kaist"
  },
  {
    "institution": "Sungkyunkwan University",
    "degree": "Undergraduate · Double major",
    "date": "2015.03 – 2023.07",
    "majors": [
      "Advanced Materials Science and Engineering",
      "Culture and Technology"
    ],
    "note": "Cum Laude",
    "thesis": {
      "title": "Empowering wearables: Harnessing human energy for self-generating devices"
    },
    "advisorId": "kim",
    "organizationId": "skku"
  }
];
export const cv = {"title":"Curriculum vitae","subtitle":"Sensor fabrication · Sensing toolkits","headings":{"profile":"Profile","education":"Education"}};
export const cvSections: CVSection[] = [
  {
    "id": "research-experience",
    "title": "Research Experience",
    "entries": [
      {
        "title": "Research Intern · HCI Tech Lab",
        "subtitle": "KAIST",
        "date": "2023.06 – 2023.08",
        "year": "2023",
        "description": "",
        "selected": false,
        "visible": true,
        "advisorId": "yoon",
        "links": [
          {
            "label": "Lab",
            "href": "https://hcitech.org/team",
            "kind": "other"
          }
        ],
        "sortDate": "2023-08",
        "organizationId": "kaist"
      },
      {
        "title": "Undergraduate Researcher · NESEL",
        "subtitle": "Sungkyunkwan University",
        "date": "2021.12 – 2022.06",
        "description": "Prototyped wearable triboelectric energy-harvesting devices and measured energy generated by body movement.",
        "selected": true,
        "visible": true,
        "year": "2022",
        "advisorId": "kim",
        "sortDate": "2022-06",
        "organizationId": "skku"
      }
    ],
    "groupByYear": false
  },
  {
    "id": "experience",
    "title": "Work Experience",
    "entries": [
      {
        "title": "Public Diplomacy Intern",
        "subtitle": "Embassy of the United States, Seoul",
        "date": "2022.07 – 2022.12",
        "description": "Contributed to the design and evaluation of public diplomacy programs and supported program planning.",
        "selected": true,
        "visible": true,
        "year": "2022",
        "sortDate": "2022-12",
        "organizationId": "us-embassy"
      },
      {
        "id": "katusa",
        "title": "ROKA Staff Office · HR & Interpreter",
        "subtitle": "U.S. Army · KATUSA",
        "date": "2016.05 – 2018.02",
        "year": "2018",
        "sortDate": "2018-02",
        "description": "Provided Korean–English interpretation, document translation, and personnel administration as a KATUSA.",
        "visible": true,
        "selected": false,
        "organizationId": "us-army"
      }
    ],
    "groupByYear": false
  },
  {
    "id": "industry-projects",
    "title": "Selected Projects",
    "entries": [
      {
        "title": "Everwhite (Winter is Coming)",
        "subtitle": "Interaction design project",
        "date": "2022.10 – 2023.01",
        "description": "Redesigned the user experience and replanned interactions for a shared VR snowball-fighting experience with thermal and tactile feedback.",
        "selected": false,
        "visible": true,
        "projectSlug": "everwhite",
        "details": [],
        "id": "everwhite",
        "year": "2023",
        "sortDate": "2023-01"
      },
      {
        "title": "Student’s Plan",
        "subtitle": "Sungkyunkwan University · Samsung Electronics",
        "date": "2021.08 – 2021.12",
        "description": "Conducted user interviews and developed a dormitory-focused appliance experience in an industry–university collaboration with Samsung Electronics.",
        "selected": false,
        "visible": true,
        "id": "qooker",
        "year": "2021",
        "advisorId": "sul",
        "details": [],
        "sortDate": "2021-12",
        "image": "/images/projects/students-plan.png",
        "imageAlt": "Student’s Plan: dormitory meal-kit stock, shared Qooker availability, and meal logs.",
        "imageAspectRatio": "2 / 1"
      },
      {
        "title": "Play Pacific",
        "subtitle": "Sungkyunkwan University · Amorepacific",
        "date": "2022.03 – 2022.07",
        "description": "Planned interactive exhibition content using a PPG wearable and user-experience evaluation measures.",
        "selected": false,
        "visible": true,
        "year": "2022",
        "advisorId": "sul",
        "details": [],
        "sortDate": "2022-07"
      },
      {
        "title": "Giview",
        "subtitle": "Sungkyunkwan University · Korea Food for the Hungry International (KFHI)",
        "date": "2022.03 – 2022.07",
        "description": "Proposed an OTT-based micro-donation service to improve the donation experience through an industry–university collaboration with KFHI.",
        "selected": false,
        "visible": true,
        "id": "giview",
        "advisorId": "lee",
        "details": [],
        "year": "2022",
        "sortDate": "2022-07"
      },
      {
        "title": "Soundinity",
        "subtitle": "Sungkyunkwan University · Wavedeck",
        "date": "2022.06 – 2022.12",
        "description": "Led a six-person team exploring AI-generated ambient sounds for Unity in an industry–university collaboration with Wavedeck.",
        "selected": true,
        "visible": true,
        "id": "soundinity",
        "year": "2022",
        "advisorId": "ko",
        "details": [],
        "projectSlug": "soundinity",
        "sortDate": "2022-12"
      },
      {
        "id": "jeogiyo",
        "title": "Jeogiyo",
        "subtitle": "Sungkyunkwan University",
        "year": "2021",
        "date": "2021.08 – 2021.11",
        "sortDate": "2021-11",
        "description": "Proposed a platform connecting students and campus-area shops through stories, reviews, and local discovery.",
        "selected": false,
        "visible": true,
        "advisorId": "lee",
        "details": [],
        "image": "/images/projects/jeogiyo.png",
        "imageAlt": "Jeogiyo concept: students share stories and reviews, while campus-area shops receive keywords, trends, and feedback.",
        "imageAspectRatio": "16 / 9"
      },
      {
        "id": "wandering-seoul",
        "title": "Wandering Seoul: A Midsummer Fantasia",
        "subtitle": "Sungkyunkwan University",
        "year": "2021",
        "date": "2021.03 – 2021.06",
        "sortDate": "2021-06",
        "description": "Planned a mixed-reality story tour for visitors to Seoul, using smartphone location services and augmented reality to layer fictional spaces and stories onto the city.",
        "selected": false,
        "visible": true,
        "advisorId": "kim-jiyeon",
        "details": []
      }
    ]
  },
  {
    "id": "honors",
    "title": "Academic Honors",
    "entries": [
      {
        "title": "Creative Scholarship ($4.5k)",
        "subtitle": "Sungkyunkwan University",
        "date": "",
        "description": "Recommended by the College of Engineering Scholarship Committee.",
        "selected": true,
        "visible": true,
        "year": "2021"
      },
      {
        "title": "Academic Merit Scholarship",
        "subtitle": "Advanced Materials Science and Engineering · Sungkyunkwan University",
        "date": "Spring",
        "description": "",
        "selected": false,
        "visible": true,
        "year": "2022",
        "sortDate": "2022-03"
      },
      {
        "title": "Dean’s List",
        "subtitle": "Sungkyunkwan University",
        "year": "2021",
        "date": "Spring",
        "description": "",
        "selected": true,
        "visible": true,
        "sortDate": "2021-03"
      },
      {
        "title": "Dean’s List",
        "subtitle": "Sungkyunkwan University",
        "year": "2020",
        "date": "Fall",
        "description": "",
        "selected": true,
        "visible": true,
        "sortDate": "2020-09"
      }
    ]
  },
  {
    "id": "design-awards",
    "title": "Awards",
    "entries": [
      {
        "title": "1st Prize · AI Ideathon on Low-Quality Speech Data",
        "subtitle": "Ministry of Science and ICT (MSIT) · National Information Society Agency (NIA) · Tmax Enterprise",
        "date": "2022.01",
        "description": "",
        "selected": false,
        "visible": true,
        "url": "https://www.lecturernews.com/news/articleView.html?idxno=86100",
        "urlLabel": "News",
        "details": [
          {
            "label": "Project",
            "value": "Audio noise effects using low-quality speech data"
          }
        ],
        "image": "/images/projects/speech-noise.png",
        "imageAlt": "Concept: separate voice and noise, build a contextual noise library, and apply noise filters.",
        "id": "speech-award",
        "year": "2022",
        "sortDate": "2022-01"
      },
      {
        "title": "1st Prize · Everyday Video Data Hackathon",
        "subtitle": "Ministry of Science and ICT (MSIT) · National Information Society Agency (NIA) · Metrix",
        "date": "2021.12",
        "description": "",
        "selected": false,
        "visible": true,
        "year": "2021",
        "url": "https://www.wowtv.co.kr/NewsCenter/News/Read?articleId=A202112220210",
        "urlLabel": "News",
        "sortDate": "2021-12-16",
        "image": "/images/projects/3d-map.png",
        "imageAlt": "Concept: turn vlog frames into 3D meshes and a metaverse map.",
        "id": "video-award"
      },
      {
        "title": "Idea Award · Creative Bridge Festival",
        "subtitle": "Seoul Campus Town · Jongno-gu · SKKU Startup Support Foundation · SKKU Campus Town · SKKU Convergence Institute for Culture, Arts, and Media",
        "date": "2021.10",
        "description": "",
        "selected": false,
        "visible": true,
        "year": "2021",
        "details": [
          {
            "label": "Project",
            "value": "Wandering Seoul: A Midsummer Fantasia"
          }
        ],
        "sortDate": "2021-10",
        "relatedEntryId": "wandering-seoul",
        "links": []
      },
      {
        "title": "Excellence Award · Fourth Industrial Revolution Talent Development Joint Festival Competition",
        "subtitle": "Korea Society of Information Communication Security Ethics",
        "date": "2021.11",
        "description": "",
        "selected": false,
        "visible": true,
        "year": "2021",
        "relatedEntryId": "jeogiyo",
        "details": [
          {
            "label": "Category",
            "value": "Startup Ideas"
          },
          {
            "label": "Project",
            "value": "Jeogiyo"
          }
        ],
        "links": [],
        "sortDate": "2021-11"
      },
      {
        "title": "1st Prize · DNA-HERO",
        "subtitle": "Ministry of Trade, Industry and Energy (MOTIE) · Korea Institute for Advancement of Technology (KIAT) · SKKU Innovation Center for Engineering Education",
        "date": "2022.12",
        "description": "",
        "selected": false,
        "visible": true,
        "relatedEntryId": "soundinity",
        "year": "2022",
        "id": "dna-hero-award",
        "sortDate": "2022-12"
      },
      {
        "title": "Encouragement Award · SKKU Undergraduate PBL Course Project Competition",
        "subtitle": "SKKU AI Innovation Sharing University Project Group",
        "year": "2022",
        "date": "2022.01",
        "description": "",
        "selected": false,
        "visible": true,
        "relatedEntryId": "qooker",
        "details": [
          {
            "label": "Project",
            "value": "Student’s Plan"
          }
        ],
        "sortDate": "2022-01"
      },
      {
        "title": "1st Prize · Culture and Technology Major Day Capstone Project Competition",
        "subtitle": "College of Software · Sungkyunkwan University",
        "date": "2022.12",
        "description": "",
        "selected": false,
        "visible": true,
        "relatedEntryId": "giview",
        "year": "2022",
        "details": [
          {
            "label": "Project",
            "value": "Giview"
          }
        ],
        "sortDate": "2022-12-19"
      },
      {
        "id": "ixda-finalist",
        "title": "Finalist · IxDA Interaction Awards",
        "subtitle": "Connecting category",
        "date": "2023.03",
        "year": "2023",
        "description": "",
        "selected": true,
        "visible": true,
        "relatedEntryId": "everwhite",
        "url": "https://awards.ixda.org/projects/everwhite.html",
        "urlLabel": "Project",
        "sortDate": "2023-03"
      }
    ]
  },
  {
    "id": "talks",
    "title": "Invited Talks & Lectures",
    "entries": [
      {
        "title": "Multisensory XR Workshop",
        "subtitle": "Hongik University · Biohealth program",
        "date": "2023.02.11 – 2023.02.12",
        "description": "Contributed to delivery of a two-day XR workshop for university students.",
        "selected": false,
        "visible": true,
        "year": "2023",
        "sortDate": "2023-02-12"
      },
      {
        "title": "Invited Talk · DNA-X Talent Vision Camp",
        "subtitle": "SKKU Innovation Center for Engineering Education",
        "date": "2023.06.02",
        "description": "Invited to share the DNA-HERO industry collaboration experience following the 2022 1st Prize.",
        "selected": false,
        "visible": true,
        "year": "2023",
        "sortDate": "2023-06-02"
      }
    ]
  },
  {
    "id": "media",
    "title": "Media",
    "entries": [
      {
        "title": "Interview · SKKU Webzine",
        "subtitle": "Sungkyunkwan University",
        "date": "2022.01",
        "year": "2022",
        "description": "",
        "selected": false,
        "visible": true,
        "url": "https://webzine.skku.edu/skkuzine/section/people01.do?articleNo=94837&article.offset=0&articleLimit=10",
        "urlLabel": "Interview",
        "sortDate": "2022-01"
      }
    ]
  },
  {
    "id": "personal",
    "title": "Personal",
    "entries": [
      {
        "title": "Paperball",
        "subtitle": "Honorable Mention · 29th KAIST Literary Award · Screenplay",
        "date": "",
        "description": "Submitted to the 2023 competition; results announced in 2024.",
        "selected": false,
        "visible": true,
        "url": "https://times.kaist.ac.kr/news/articleView.html?idxno=21551",
        "year": "2024",
        "urlLabel": "Article"
      }
    ],
    "intro": "Outside research, I enjoy writing fiction and screenplays."
  }
];
